name: gocan

on:
  push:
    branches: [main]
    paths:
      - 'gocan.rb'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11]
    steps:
    - uses: actions/checkout@v2
    
    - name: run the test
      run: ./test/gocan-test.sh