name: gocan

on:
  push:
    branches: [main]
    #paths:
    #  - 'gocan.rb'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: run the test
      run: ./test/gocan-test.sh